// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC05TwrL7NDJ1DIKQ7SgDTthDcvKWkviZc',
    appId: '1:1052779949245:web:c7918c7786eef1d9c45bd4',
    messagingSenderId: '1052779949245',
    projectId: 'corim-apex',
    authDomain: 'corim-apex.firebaseapp.com',
    storageBucket: 'corim-apex.firebasestorage.app',
    measurementId: 'G-3HW8GNKWHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmp5HOJ-_hd73SVUtKrKkXQameIfSSr8',
    appId: '1:1052779949245:android:96be83bf7bc6247ec45bd4',
    messagingSenderId: '1052779949245',
    projectId: 'corim-apex',
    storageBucket: 'corim-apex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBddI1xP7iQgTe9aCwMwalRFQiI7KBUnhA',
    appId: '1:1052779949245:ios:bf16d2baef3c34fac45bd4',
    messagingSenderId: '1052779949245',
    projectId: 'corim-apex',
    storageBucket: 'corim-apex.firebasestorage.app',
    iosBundleId: 'com.example.corim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBddI1xP7iQgTe9aCwMwalRFQiI7KBUnhA',
    appId: '1:1052779949245:ios:bf16d2baef3c34fac45bd4',
    messagingSenderId: '1052779949245',
    projectId: 'corim-apex',
    storageBucket: 'corim-apex.firebasestorage.app',
    iosBundleId: 'com.example.corim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC05TwrL7NDJ1DIKQ7SgDTthDcvKWkviZc',
    appId: '1:1052779949245:web:2d4c562d32b3e3d6c45bd4',
    messagingSenderId: '1052779949245',
    projectId: 'corim-apex',
    authDomain: 'corim-apex.firebaseapp.com',
    storageBucket: 'corim-apex.firebasestorage.app',
    measurementId: 'G-T82E9F40KH',
  );
}
